<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Simple Linear Regression | Machine Learning with TidyModels</title>
  <meta name="description" content="This is a primer on various ML modeling techniques and the tidymodels</code>
syntax and workflow for leveraging these techniques.</p>" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Simple Linear Regression | Machine Learning with TidyModels" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a primer on various ML modeling techniques and the tidymodels</code>
syntax and workflow for leveraging these techniques.</p>" />
  <meta name="github-repo" content="ericwburden/machine-learning-with-tidymodels" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Simple Linear Regression | Machine Learning with TidyModels" />
  
  <meta name="twitter:description" content="This is a primer on various ML modeling techniques and the tidymodels</code>
syntax and workflow for leveraging these techniques.</p>" />
  

<meta name="author" content="Eric Burden" />


<meta name="date" content="2022-11-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chapter-2.html"/>
<link rel="next" href="chapter-4.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Notes on Tidymodels</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#ch1-software_used"><i class="fa fa-check"></i><b>1.1</b> Software Used</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapter-2.html"><a href="chapter-2.html"><i class="fa fa-check"></i><b>2</b> The Tidymodels Workflow</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chapter-2.html"><a href="chapter-2.html#ch2-about-tidymodels"><i class="fa fa-check"></i><b>2.1</b> About Tidymodels</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="chapter-2.html"><a href="chapter-2.html#ch2-reuse-existing-data-structures"><i class="fa fa-check"></i><b>2.1.1</b> Re-use existing data structures</a></li>
<li class="chapter" data-level="2.1.2" data-path="chapter-2.html"><a href="chapter-2.html#ch2-simple-functions-with-pipes"><i class="fa fa-check"></i><b>2.1.2</b> Compose simple functions with pipes</a></li>
<li class="chapter" data-level="2.1.3" data-path="chapter-2.html"><a href="chapter-2.html#ch2-embrace-functional-programming"><i class="fa fa-check"></i><b>2.1.3</b> Embrace functional programming</a></li>
<li class="chapter" data-level="2.1.4" data-path="chapter-2.html"><a href="chapter-2.html#ch2-design-for-humans"><i class="fa fa-check"></i><b>2.1.4</b> Design for humans</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="chapter-2.html"><a href="chapter-2.html#ch2-philosophy-in-practice"><i class="fa fa-check"></i><b>2.2</b> Philosophy in Practice</a></li>
<li class="chapter" data-level="2.3" data-path="chapter-2.html"><a href="chapter-2.html#ch2-workflow-steps"><i class="fa fa-check"></i><b>2.3</b> Workflow Steps</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="chapter-2.html"><a href="chapter-2.html#ch2-data-splitting"><i class="fa fa-check"></i><b>2.3.1</b> Data Splitting</a></li>
<li class="chapter" data-level="2.3.2" data-path="chapter-2.html"><a href="chapter-2.html#ch2-data-preparation"><i class="fa fa-check"></i><b>2.3.2</b> Data Preparation</a></li>
<li class="chapter" data-level="2.3.3" data-path="chapter-2.html"><a href="chapter-2.html#ch2-model-specification"><i class="fa fa-check"></i><b>2.3.3</b> Model Specification</a></li>
<li class="chapter" data-level="2.3.4" data-path="chapter-2.html"><a href="chapter-2.html#ch2-bundling-a-workflow"><i class="fa fa-check"></i><b>2.3.4</b> Bundling a Workflow</a></li>
<li class="chapter" data-level="2.3.5" data-path="chapter-2.html"><a href="chapter-2.html#ch2-checking-results"><i class="fa fa-check"></i><b>2.3.5</b> Checking Results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter-3.html"><a href="chapter-3.html"><i class="fa fa-check"></i><b>3</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chapter-3.html"><a href="chapter-3.html#ch3-description"><i class="fa fa-check"></i><b>3.1</b> Description</a></li>
<li class="chapter" data-level="3.2" data-path="chapter-3.html"><a href="chapter-3.html#ch3-how-it-works"><i class="fa fa-check"></i><b>3.2</b> How it Works</a></li>
<li class="chapter" data-level="3.3" data-path="chapter-3.html"><a href="chapter-3.html#ch3-evaluating-validity"><i class="fa fa-check"></i><b>3.3</b> Evaluating Validity</a></li>
<li class="chapter" data-level="3.4" data-path="chapter-3.html"><a href="chapter-3.html#ch3-evaluating-fit"><i class="fa fa-check"></i><b>3.4</b> Evaluating Fit</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="chapter-3.html"><a href="chapter-3.html#ch3-residual-standard-error"><i class="fa fa-check"></i><b>3.4.1</b> Residual Standard Error</a></li>
<li class="chapter" data-level="3.4.2" data-path="chapter-3.html"><a href="chapter-3.html#ch3-rsq-statistic"><i class="fa fa-check"></i><b>3.4.2</b> <span class="math inline">\(R^2\)</span> Statistic</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="chapter-3.html"><a href="chapter-3.html#ch3-example"><i class="fa fa-check"></i><b>3.5</b> Example</a></li>
<li class="chapter" data-level="3.6" data-path="chapter-3.html"><a href="chapter-3.html#ch3-considerations"><i class="fa fa-check"></i><b>3.6</b> Considerations</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="chapter-3.html"><a href="chapter-3.html#ch3-limits-of-applicability"><i class="fa fa-check"></i><b>3.6.1</b> Limits of Applicability</a></li>
<li class="chapter" data-level="3.6.2" data-path="chapter-3.html"><a href="chapter-3.html#ch3-outliers"><i class="fa fa-check"></i><b>3.6.2</b> Outliers</a></li>
<li class="chapter" data-level="3.6.3" data-path="chapter-3.html"><a href="chapter-3.html#ch3-high-leverage-points"><i class="fa fa-check"></i><b>3.6.3</b> High-leverage points</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chapter-4.html"><a href="chapter-4.html"><i class="fa fa-check"></i><b>4</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chapter-4.html"><a href="chapter-4.html#ch4-description"><i class="fa fa-check"></i><b>4.1</b> Description</a></li>
<li class="chapter" data-level="4.2" data-path="chapter-4.html"><a href="chapter-4.html#ch4-how-it-works"><i class="fa fa-check"></i><b>4.2</b> How it Works</a></li>
<li class="chapter" data-level="4.3" data-path="chapter-4.html"><a href="chapter-4.html#ch4-evaluating-validity"><i class="fa fa-check"></i><b>4.3</b> Evaluating Validity</a></li>
<li class="chapter" data-level="4.4" data-path="chapter-4.html"><a href="chapter-4.html#ch4-identifying-important-predictors"><i class="fa fa-check"></i><b>4.4</b> Identifying Important Predictors</a></li>
<li class="chapter" data-level="4.5" data-path="chapter-4.html"><a href="chapter-4.html#ch4-evaluating-fit"><i class="fa fa-check"></i><b>4.5</b> Evaluating Fit</a></li>
<li class="chapter" data-level="4.6" data-path="chapter-4.html"><a href="chapter-4.html#ch4-example"><i class="fa fa-check"></i><b>4.6</b> Example</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="chapter-4.html"><a href="chapter-4.html#ch-correlated-predictors"><i class="fa fa-check"></i><b>4.6.1</b> Correlated Predictors</a></li>
<li class="chapter" data-level="4.6.2" data-path="chapter-4.html"><a href="chapter-4.html#ch4-tidymodels-workflow"><i class="fa fa-check"></i><b>4.6.2</b> Tidymodels Workflow</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="chapter-4.html"><a href="chapter-4.html#ch4-considerations"><i class="fa fa-check"></i><b>4.7</b> Considerations</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="chapter-4.html"><a href="chapter-4.html#ch4-not-just-combining-simple-models"><i class="fa fa-check"></i><b>4.7.1</b> Not Just Combining Simple Models</a></li>
<li class="chapter" data-level="4.7.2" data-path="chapter-4.html"><a href="chapter-4.html#ch4-qualitative-variables"><i class="fa fa-check"></i><b>4.7.2</b> Qualitative Variables</a></li>
<li class="chapter" data-level="4.7.3" data-path="chapter-4.html"><a href="chapter-4.html#ch4-predictor-interactions"><i class="fa fa-check"></i><b>4.7.3</b> Predictor Interactions</a></li>
<li class="chapter" data-level="4.7.4" data-path="chapter-4.html"><a href="chapter-4.html#ch4-polynomial-regression"><i class="fa fa-check"></i><b>4.7.4</b> Polynomial Regression</a></li>
<li class="chapter" data-level="4.7.5" data-path="chapter-4.html"><a href="chapter-4.html#ch4-potential-issues"><i class="fa fa-check"></i><b>4.7.5</b> Potential Issues</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chapter-5.html"><a href="chapter-5.html"><i class="fa fa-check"></i><b>5</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chapter-5.html"><a href="chapter-5.html#ch5-description"><i class="fa fa-check"></i><b>5.1</b> Description</a></li>
<li class="chapter" data-level="5.2" data-path="chapter-5.html"><a href="chapter-5.html#ch5-how-it-works"><i class="fa fa-check"></i><b>5.2</b> How it Works</a></li>
<li class="chapter" data-level="5.3" data-path="chapter-5.html"><a href="chapter-5.html#ch5-evaluating-validity"><i class="fa fa-check"></i><b>5.3</b> Evaluating Validity</a></li>
<li class="chapter" data-level="5.4" data-path="chapter-5.html"><a href="chapter-5.html#ch5-evaluating-fit"><i class="fa fa-check"></i><b>5.4</b> Evaluating Fit</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="chapter-5.html"><a href="chapter-5.html#ch5-binomial-logistic-regression"><i class="fa fa-check"></i><b>5.4.1</b> Binomial Logistic Regression</a></li>
<li class="chapter" data-level="5.4.2" data-path="chapter-5.html"><a href="chapter-5.html#ch5-multinomial-logistic-regression"><i class="fa fa-check"></i><b>5.4.2</b> Multinomial Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="chapter-5.html"><a href="chapter-5.html#ch5-example"><i class="fa fa-check"></i><b>5.5</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>6</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Machine Learning with TidyModels</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter-3" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Simple Linear Regression<a href="chapter-3.html#chapter-3" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="ch3-description" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Description<a href="chapter-3.html#ch3-description" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>An approach for predicting a dependent (response) value <span class="math inline">\(Y\)</span> based on a single
independent (predictor) value <span class="math inline">\(X\)</span>, given that there is some proportional linear
relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. That is, assuming that one unit of change in <span class="math inline">\(X\)</span>
results in a consistent change (increase or decrease) in <span class="math inline">\(Y\)</span>.</p>
<p><span class="math display">\[Y \approx \beta_0 + \beta_1X\]</span></p>
<p>In this equation, <span class="math inline">\(\beta_0\)</span> represents a constant offset (the <em>intercept</em>) and <span class="math inline">\(\beta_1\)</span>
represents the amount <span class="math inline">\(Y\)</span> changes for each change in <span class="math inline">\(X\)</span> (the <em>slope</em>). In a <strong>Simple
Linear Regression</strong> model, the goal is to estimate <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span>
within the observed range of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> values such that the predicted values of <span class="math inline">\(Y\)</span>
are as close to the actual <span class="math inline">\(Y\)</span> values as possible, generally determined by minimizing
the <em>Residual Sum of Squares</em>.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
</div>
<div id="ch3-how-it-works" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> How it Works<a href="chapter-3.html#ch3-how-it-works" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Given that the goal is to estimate the <em>slope</em> and <em>intercept</em> of the linear formula
representation and that we have a series of <span class="math inline">\(X/Y\)</span> observations, the values of <span class="math inline">\(\beta_0\)</span>
and <span class="math inline">\(\beta_1\)</span> can be estimated via</p>
<p><span class="math display">\[\hat\beta_1 = \frac{\sum_{i=1}^n(x_i - \bar{x})(y_i-\bar{y})}{\sum_{i=1}^n(x_i-\bar{x})^2}\]</span>
<span class="math display">\[\hat\beta_0 = \bar{y} - \hat\beta_1\bar{x}\]</span> In code, this looks like:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="chapter-3.html#cb15-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> mtcars<span class="sc">$</span>hp  <span class="co"># horsepower</span></span>
<span id="cb15-2"><a href="chapter-3.html#cb15-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> mtcars<span class="sc">$</span>mpg <span class="co"># fuel efficiency, in miles/gallon</span></span>
<span id="cb15-3"><a href="chapter-3.html#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="chapter-3.html#cb15-4" aria-hidden="true" tabindex="-1"></a>mean_diff <span class="ot">&lt;-</span> \(x) x <span class="sc">-</span> <span class="fu">mean</span>(x)</span>
<span id="cb15-5"><a href="chapter-3.html#cb15-5" aria-hidden="true" tabindex="-1"></a>slope     <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">mean_diff</span>(x) <span class="sc">*</span> <span class="fu">mean_diff</span>(y))<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">mean_diff</span>(x)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb15-6"><a href="chapter-3.html#cb15-6" aria-hidden="true" tabindex="-1"></a>intercept <span class="ot">&lt;-</span> <span class="fu">mean</span>(y) <span class="sc">-</span> slope <span class="sc">*</span> <span class="fu">mean</span>(x)</span>
<span id="cb15-7"><a href="chapter-3.html#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="chapter-3.html#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualization. The line demonstrates the simple </span></span>
<span id="cb15-9"><a href="chapter-3.html#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># linear regression fit as calculated above.</span></span>
<span id="cb15-10"><a href="chapter-3.html#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars, <span class="fu">aes</span>(hp, mpg)) <span class="sc">+</span></span>
<span id="cb15-11"><a href="chapter-3.html#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-12"><a href="chapter-3.html#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> slope, <span class="at">intercept =</span> intercept, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-13"><a href="chapter-3.html#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(</span>
<span id="cb15-14"><a href="chapter-3.html#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="dv">300</span>, <span class="at">y =</span> <span class="fl">12.5</span>, </span>
<span id="cb15-15"><a href="chapter-3.html#cb15-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">label =</span> <span class="fu">glue</span>(<span class="st">&quot;Slope: {round(slope, 2)}</span><span class="sc">\n</span><span class="st">Intercept: {round(intercept, 2)}&quot;</span>)</span>
<span id="cb15-16"><a href="chapter-3.html#cb15-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-17"><a href="chapter-3.html#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-18"><a href="chapter-3.html#cb15-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Simple Linear Regression&quot;</span>,</span>
<span id="cb15-19"><a href="chapter-3.html#cb15-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Horsepower&quot;</span>,</span>
<span id="cb15-20"><a href="chapter-3.html#cb15-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Miles/Gallon&quot;</span></span>
<span id="cb15-21"><a href="chapter-3.html#cb15-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-22"><a href="chapter-3.html#cb15-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>So, for a single predictor variable, <em>slope</em> and <em>intercept</em> can be estimated by a
<em>relatively</em> straightforward algorithm.</p>
</div>
<div id="ch3-evaluating-validity" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Evaluating Validity<a href="chapter-3.html#ch3-evaluating-validity" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It is possible to estimate the <em>Standard Error</em><a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>
([[Definitions#^72c250|definition]]) of a model using the formulae below:</p>
<p><span class="math display">\[e_1 = y_1 - \hat\beta_0 - \hat\beta_1x_1\]</span> <span class="math display">\[RSS = e_1^2 + e_2^2 + ... + e_n^2\]</span>
<span class="math display">\[\sigma \approx RSE = \sqrt{RSS/(n-2)}\]</span>
<span class="math display">\[\widehat{SE}(\hat\beta_0)^2 = \sigma^2\left[\frac{1}{n}+\frac{\bar{x}^2}{\sum_{i=1}^n{(x_i - \bar{x})^2}}\right]\]</span>
<span class="math display">\[\widehat{SE}(\hat\beta_1)^2 = \frac{\sigma^2}{\sum_{i=1}^n{(x_i - \bar{x})^2}}\]</span></p>
<p>In code, that looks like:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="chapter-3.html#cb16-1" aria-hidden="true" tabindex="-1"></a>predicted  <span class="ot">&lt;-</span> (slope <span class="sc">*</span> x) <span class="sc">+</span> intercept</span>
<span id="cb16-2"><a href="chapter-3.html#cb16-2" aria-hidden="true" tabindex="-1"></a>residuals  <span class="ot">&lt;-</span> predicted <span class="sc">-</span> y</span>
<span id="cb16-3"><a href="chapter-3.html#cb16-3" aria-hidden="true" tabindex="-1"></a>rss        <span class="ot">&lt;-</span> <span class="fu">sum</span>(residuals<span class="sc">^</span><span class="dv">2</span>)               <span class="co"># residual sum of squares</span></span>
<span id="cb16-4"><a href="chapter-3.html#cb16-4" aria-hidden="true" tabindex="-1"></a>n          <span class="ot">&lt;-</span> <span class="fu">length</span>(x)                      <span class="co"># number of observations</span></span>
<span id="cb16-5"><a href="chapter-3.html#cb16-5" aria-hidden="true" tabindex="-1"></a>rse        <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(rss <span class="sc">/</span> (n_observed <span class="sc">-</span> <span class="dv">2</span>))   <span class="co"># residual standard error</span></span>
<span id="cb16-6"><a href="chapter-3.html#cb16-6" aria-hidden="true" tabindex="-1"></a>se_intcpt  <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(rse<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> ((<span class="dv">1</span><span class="sc">/</span>n) <span class="sc">+</span> (<span class="fu">mean</span>(x)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">2</span>))))</span>
<span id="cb16-7"><a href="chapter-3.html#cb16-7" aria-hidden="true" tabindex="-1"></a>se_slope   <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(rse<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div>
<p>The 95% confidence interval (for the slope, in this example) can be given by:
<span class="math display">\[\hat\beta_1 \pm 2 \times SE(\hat\beta_1)\]</span></p>
<p>From the above example, it looks like this in code:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="chapter-3.html#cb17-1" aria-hidden="true" tabindex="-1"></a>min_interval  <span class="ot">&lt;-</span> slope <span class="sc">-</span> (<span class="dv">2</span> <span class="sc">*</span> se_slope)</span>
<span id="cb17-2"><a href="chapter-3.html#cb17-2" aria-hidden="true" tabindex="-1"></a>max_interval  <span class="ot">&lt;-</span> slope <span class="sc">+</span> (<span class="dv">2</span> <span class="sc">*</span> se_slope)</span>
<span id="cb17-3"><a href="chapter-3.html#cb17-3" aria-hidden="true" tabindex="-1"></a>(conf_interval <span class="ot">&lt;-</span> <span class="fu">c</span>(min_interval, max_interval))</span></code></pre></div>
<pre><code>## [1] -0.08846689 -0.04798967</code></pre>
<p>We find that we can say with 95% confidence that the slope lies somewhere between
-0.0884669 and -0.0479897, which is reasonably close to our input value. Is
this enough to determine whether our <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are related? For that, we can calculate
the <em>t-statistic</em><a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> by:</p>
<p><span class="math display">\[t = \frac{\hat\beta_1 - 0}{SE(\hat\beta_1)}\]</span></p>
<p>to measure the number of standard deviations that <span class="math inline">\(\hat\beta_1\)</span> is away from <code>0</code>. This
<em>t-statistic</em> is further used to compute the <em>p-value</em><a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a>. In general, small <em>p-values</em>
indicate that it is unlikely to observe a substantial association between the predictor
and response due to random chance, as opposed to a real association. While it is
possible to easily calculate the <em>t-statistic</em>, finding the <em>p-value</em> generally requires
a lookup in a <em>t-distribution table</em>. Thankfully, R can handle that bit for you, as
we’ll see in the <code>tidymodels</code> example for this modeling approach.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="chapter-3.html#cb19-1" aria-hidden="true" tabindex="-1"></a>(t_statistic <span class="ot">&lt;-</span> (slope <span class="sc">-</span> <span class="dv">0</span>)<span class="sc">/</span>se_slope)</span></code></pre></div>
<pre><code>## [1] -6.742389</code></pre>
<p>The important part here is that a low <em>p-value</em> indicates that your model fit is,
actually, applicable for the data you have applied the model to, which is ultimately the
part we are interested in.</p>
</div>
<div id="ch3-evaluating-fit" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Evaluating Fit<a href="chapter-3.html#ch3-evaluating-fit" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the previous section, we saw reference to <span class="math inline">\(e\)</span> as the difference between the observed
and predicted response value for a given predictor value. For real data that can be fit
by a linear regression, it’s better to assume that the actual formula is more like
<span class="math display">\[ Y \approx \beta_0 + \beta_1X + \epsilon\]</span> where <span class="math inline">\(\epsilon\)</span> represents an “error
term”, that is, the accumulation of <strong>all</strong> the unknown variables and errors that are
affecting the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. This accounts, in a sort of
<em>hand-waving</em> way, for differences between the predicted linear relationship and
observed results. The quality of a linear regression fit, which is how well the slope
and intercept have been estimated, can be determined from the <em>residual standard error</em>
(which we calculated previously) and the <span class="math inline">\(R^2\)</span> statistic. Of the two, the <span class="math inline">\(R^2\)</span>
statistic is more useful and easily understood.</p>
<div id="ch3-residual-standard-error" class="section level3 hasAnchor" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Residual Standard Error<a href="chapter-3.html#ch3-residual-standard-error" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <em>residual standard error</em> (RSE), that is, the standard error for the observed
residuals from the linear regression fit, is an estimate of the standard deviation of
the error term above. It can be calculated via:</p>
<p><span class="math display">\[e_1 = y_1 - \hat\beta_0 - \hat\beta_1x_1\]</span> <span class="math display">\[RSS = e_1^2 + e_2^2 + ... + e_n^2\]</span>
<span class="math display">\[\sigma \approx RSE = \sqrt{RSS/(n-2)}\]</span></p>
<p>In general, a smaller RSE indicates a better fit of the data. RSE, however, is an
absolute measure of the lack of fit measured in the same units as <span class="math inline">\(Y\)</span>, indicating how
far off any given predicted <span class="math inline">\(Y\)</span> value may be.</p>
</div>
<div id="ch3-rsq-statistic" class="section level3 hasAnchor" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> <span class="math inline">\(R^2\)</span> Statistic<a href="chapter-3.html#ch3-rsq-statistic" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Contrasted to RSE, <span class="math inline">\(R^2\)</span> represents the <em>proportion</em> of variance explained by the error
term and is always a value between 0 and 1. It can be calculated by:</p>
<p><span class="math display">\[TSS = \sum{(y_i - \bar{y})^2}\]</span> <span class="math display">\[R^2 = \frac{TSS - RSS}{TSS} = 1 - \frac{RSS}{TSS}\]</span></p>
<p>where TSS is the <em>total sum of squares</em> of the response values and RSS is the <em>residual
sum of squares</em> (discussed above). TSS is a measure of the variability in <span class="math inline">\(Y\)</span>, whereas
RSS is a measure of the variability that is left unexplained after performing the
regression. In summary, this means that <span class="math inline">\(R^2\)</span> measures the proportion of variability in
<span class="math inline">\(Y\)</span> that can be explained using <span class="math inline">\(X\)</span>. Thus, an <span class="math inline">\(R^2\)</span> close to 1 indicates a linear
regression fit where most of the variability in the response is explained by the
regression.</p>
</div>
</div>
<div id="ch3-example" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Example<a href="chapter-3.html#ch3-example" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now, with an understanding of the underlying math and relevant statistics, we can fit a
simple linear model to the example dataset we’ve used thus far, that is: estimating the
fuel efficiency of a vehicle from its horsepower rating.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="chapter-3.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># In this example, we&#39;ll forgo the training/testing split to</span></span>
<span id="cb21-2"><a href="chapter-3.html#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># be consistent with our calculated model above.</span></span>
<span id="cb21-3"><a href="chapter-3.html#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="chapter-3.html#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Pre-process the data using a simple, no-frills recipe</span></span>
<span id="cb21-5"><a href="chapter-3.html#cb21-5" aria-hidden="true" tabindex="-1"></a>(simple_linear_recipe</span>
<span id="cb21-6"><a href="chapter-3.html#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="ot">&lt;-</span> <span class="fu">recipe</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> mtcars))</span></code></pre></div>
<pre><code>## Recipe
## 
## Inputs:
## 
##       role #variables
##    outcome          1
##  predictor          1</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="chapter-3.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setup up the model</span></span>
<span id="cb23-2"><a href="chapter-3.html#cb23-2" aria-hidden="true" tabindex="-1"></a>(simple_linear_model</span>
<span id="cb23-3"><a href="chapter-3.html#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>()</span>
<span id="cb23-4"><a href="chapter-3.html#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="sc">|&gt;</span> <span class="fu">set_engine</span>(<span class="st">&quot;lm&quot;</span>)</span>
<span id="cb23-5"><a href="chapter-3.html#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="sc">|&gt;</span> <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>))</span></code></pre></div>
<pre><code>## Linear Regression Model Specification (regression)
## 
## Computational engine: lm</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="chapter-3.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bundle the recipe and model into a workflow, fit the model</span></span>
<span id="cb25-2"><a href="chapter-3.html#cb25-2" aria-hidden="true" tabindex="-1"></a>(simple_linear_workflow</span>
<span id="cb25-3"><a href="chapter-3.html#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="ot">&lt;-</span> <span class="fu">workflow</span>()</span>
<span id="cb25-4"><a href="chapter-3.html#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="sc">|&gt;</span> <span class="fu">add_recipe</span>(simple_linear_recipe)</span>
<span id="cb25-5"><a href="chapter-3.html#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="sc">|&gt;</span> <span class="fu">add_model</span>(simple_linear_model)</span>
<span id="cb25-6"><a href="chapter-3.html#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="sc">|&gt;</span> <span class="fu">fit</span>(<span class="at">data =</span> mtcars))</span></code></pre></div>
<pre><code>## ══ Workflow [trained] ══════════════════════════════════════════════════════════════════════════════
## Preprocessor: Recipe
## Model: linear_reg()
## 
## ── Preprocessor ────────────────────────────────────────────────────────────────────────────────────
## 0 Recipe Steps
## 
## ── Model ───────────────────────────────────────────────────────────────────────────────────────────
## 
## Call:
## stats::lm(formula = ..y ~ ., data = data)
## 
## Coefficients:
## (Intercept)           hp  
##    30.09886     -0.06823</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="chapter-3.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add predictions to training data</span></span>
<span id="cb27-2"><a href="chapter-3.html#cb27-2" aria-hidden="true" tabindex="-1"></a>simple_linear_predictions <span class="ot">&lt;-</span> <span class="fu">augment</span>(simple_linear_workflow, mtcars)</span>
<span id="cb27-3"><a href="chapter-3.html#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="chapter-3.html#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate validity</span></span>
<span id="cb27-5"><a href="chapter-3.html#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(simple_linear_workflow)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)  30.1       1.63       18.4  6.64e-18
## 2 hp           -0.0682    0.0101     -6.74 1.79e- 7</code></pre>
<p>The <code>tidy</code> function (from the <code>broom</code> <span class="citation">(<a href="#ref-broom" role="doc-biblioref">Robinson, Hayes, and Couch 2022</a>)</span> package, also included in <code>tidymodels</code>)
provides a variety of coefficients related to the model, including the relevant terms,
their estimates, and the <em>p-value</em>. In this case, the <em>p-value</em>s for both the slope (of
the <code>hp</code> term, which is the only predictor variable) and the intercept are both very
small, indicating that a simple linear model is valid for making predictions on this
data set. But, how good is the fit?</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="chapter-3.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate fit</span></span>
<span id="cb29-2"><a href="chapter-3.html#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(simple_linear_predictions, mpg, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard       3.74 
## 2 rsq     standard       0.602
## 3 mae     standard       2.91</code></pre>
<p>By default, <code>yardstick</code> provides three metrics for a simple linear regression model.
<code>rmse</code> is <a href="https://en.wikipedia.org/wiki/Root-mean-square_deviation">Root-Mean-Square
Error</a>, <code>mae</code> is <a href="https://en.wikipedia.org/wiki/Mean_absolute_error">Mean
Absolute Error</a>, and <code>rsq</code> is <span class="math inline">\(R^2\)</span>,
our preferred metric for determining model fit.</p>
</div>
<div id="ch3-considerations" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Considerations<a href="chapter-3.html#ch3-considerations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="ch3-limits-of-applicability" class="section level3 hasAnchor" number="3.6.1">
<h3><span class="header-section-number">3.6.1</span> Limits of Applicability<a href="chapter-3.html#ch3-limits-of-applicability" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Predictions made using a linear regression model are <em>most</em> accurate when made within
the ranges of the observed data used to build the model. This presents a difficulty
when, for example, attempting to predict future results. Say, you want to understand
what may happen to program participation (<code>Y</code>) if the budget for your program (<code>X</code>) is
increased beyond previous levels. The further beyond the previous maximum you increase
<code>X</code>, the less likely this model is to be accurate.</p>
</div>
<div id="ch3-outliers" class="section level3 hasAnchor" number="3.6.2">
<h3><span class="header-section-number">3.6.2</span> Outliers<a href="chapter-3.html#ch3-outliers" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The presence of outliers, or observations with an unusual response value, in the data
can have an outsized impact on quality measures like RSE and <span class="math inline">\(R^2\)</span>, while not
necessarily having an equivalent impact on the fitted model parameters. Plotting
<em>studentized residuals</em> can help reveal outliers. Typically, observations whose
studentized residuals are greater than 3 should be examined and considered for
exclusion.</p>
</div>
<div id="ch3-high-leverage-points" class="section level3 hasAnchor" number="3.6.3">
<h3><span class="header-section-number">3.6.3</span> High-leverage points<a href="chapter-3.html#ch3-high-leverage-points" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Contrasted to outliers, high-leverage points have unusual <em>predictor</em> values. These
values can have an outsized impact on the fit of the model. They can be detected by
calculating the <em>leverage statistic</em>. If an observation has a leverage statistic that
greatly exceeds <span class="math inline">\((p+1)/n\)</span>, then it may be a high-leverage point. Plotting the
studentized residual vs the leverage statistic for each observation can be used to spot
outliers and high leverage points simultaneously.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-broom" class="csl-entry">
Robinson, David, Alex Hayes, and Simon Couch. 2022. <span>“Broom: Convert Statistical Objects into Tidy Tibbles.”</span> <a href="https://CRAN.R-project.org/package=broom">https://CRAN.R-project.org/package=broom</a>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Definition from <a href="https://en.wikipedia.org/wiki/Confusion_matrix">Wikipedia</a>.<a href="chapter-3.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>The standard deviation of its sampling distribution or an estimate of that
standard deviation. Accounts for one standard deviation to either side of the mean
value.<a href="chapter-3.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>In statistics, the t-statistic is the ratio of the departure of the estimated
value of a parameter from its hypothesized value to its standard error. It is used
in hypothesis testing via Student’s t-test. The t-statistic is used in a t-test to
determine whether to support or reject the null hypothesis. It is very similar to
the z-score but with the difference that t-statistic is used when the sample size is
small or the population standard deviation is unknown. For example, the t-statistic
is used in estimating the population mean from a sampling distribution of sample
means if the population standard deviation is unknown. It is also used along with
p-value when running hypothesis tests where the p-value tells us what the odds are
of the results to have happened.<a href="chapter-3.html#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>The probability of observing a result at least as extreme as the observed result
assuming the null hypothesis is correct. Put another way, it is the probability that
the observed relationship between predictor(s) and response(s) could be observed as
the result of random chance.<a href="chapter-3.html#fnref4" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chapter-2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapter-4.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/chapters/ch03-simple-linear-regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
